### ISSUE TITLE
Add WebP and AVIF support

### ISSUE THREAD

**Issue by andypost** [platformsh-templates/drupal10#104]
### What in this template can be improved or added as a feature?

Drupal has support for WebP since 9.2 ref https://www.drupal.org/node/3171135

AVIF support for read is also enough for start 

### What exactly should be updated?

Template provides support for webp out of box

### How important is this feature to you?

Nowadays Google require it

### Additional context

AVIF support could be tricky https://www.drupal.org/project/drupal/issues/3202016

**Comment by andypost** [comment]
This line needs improvement https://github.com/platformsh-templates/drupal10/blob/e548e28c4079052954dddf9421980c1475893c15/.platform.app.yaml#L117-L118

**Comment by Mupsi** [comment]
Hey @andypost! @gilzow fixes the line you highlighted; if there are additional changes required please let us know :) Thanks!
