### ISSUE TITLE
Change the main branch for templates to main

### ISSUE THREAD

**Issue by Greg-Boggs** [platformsh-templates/drupal10#57]
### Describe the bug

The main branch for all Platform.sh projects should be main. Not master. Not only because that's obviously better, but it's confusing when starting new projects on Platform to name the template branch Master and the platform project branch Main because your customer sees this when their project is creating.

Initialize environment from 'https://github.com/platformsh-templates/drupal10.git@master'

The platform project is indeed main. Platform.sh just prints @master because the template project uses @master.

### Include some logs

.

### Reproducing

Create a new blank project on platform.sh with this template.

### Expected behavior

Initialize environment from 'https://github.com/platformsh-templates/drupal10.git@main'

### Your environment

Just created an empty project

**Comment by gilzow** [comment]
Thank you for creating this issue and contributing. 

> The main branch for all Platform.sh projects should be main.

For all _new_ template repositories we have moved to using a branch name other than `master`; typically `main`. However, given the number of templates we support, and the amount of automation surrounding them, changing all repositories' default branch name is a non-trivial amount of work that we are unable to address at the moment.  

>  it's confusing when starting new projects on Platform to name the template branch Master and the platform project branch Main

Platform.sh allows you to set your default branch name to _anything_ you like, be it `main`, `'production`, etc. so your concern for confusion would still be present, even if we were to change the branch name.  What you are seeing is really the output from our system that supports custom templates based on a [template.yaml file](https://github.com/platformsh/templates-external/blob/master/template-definition.yaml). 

That said, I'll ask if outputting the branch name during initialization is necessary or could potentially be suppressed.
