### ISSUE TITLE
drush status [field] deprecated in drush 12

### ISSUE THREAD

**Issue by elgandoz** [platformsh-templates/drupal10#59]
### Describe the bug

For Drupal 10 the recommended version of drush is 12: https://www.drush.org/12.x/install/#drupal-compatibility

After upgrading to drush 12, the build were silently failing (green tick at the end) with this message in the log: "Drupal not installed. Skipping standard Drupal deploy steps"

Drush 11 already mentions the argument `[field]` for the `status` command is deprecated in favour of `--field`.
The old syntax fails in Drush 12.
**The new syntax is already compatible with drush 11.**

### Include some logs

After pushing drush 12, **on deploy:**
```shell
Executing deploy hook for application drupal
    Created Drush configuration file: /app/.drush/drush.yml
    W: 
    W:                                                                 
    W:   No arguments expected for "status" command, got "bootstrap".  
    W:                                                                 
    W: 
    Drupal not installed. Skipping standard Drupal deploy steps`
```

**Manually running the shell:**
```shell
platform ssh drush status bootstrap                                             
  No arguments expected for "status" command, got "bootstrap".                                                                  
Connection to ssh.eu-5.platform.sh closed.
```

```shell
platform ssh 'drush status --field=bootstrap'
Successful
Connection to ssh.eu-5.platform.sh closed.
```

### Reproducing

- `composer require "drush/drush:^12.1" -W`
- `drush status bootstrap`

The command should be instead
- `drush status --field=bootstrap`

### Expected behavior

A regular deploy to happen.

### Your environment

Basic installation using Drupal 10 Platform.sh project template

### Screenshots

<img width="851" alt="Screenshot 2023-07-20 at 22 29 07" src="https://github.com/platformsh-templates/drupal10/assets/5859926/da498b5d-c085-48ae-b160-504823b0a24b">

<img width="670" alt="Screenshot 2023-07-20 at 22 27 19" src="https://github.com/platformsh-templates/drupal10/assets/5859926/90cfed05-aadc-4597-bbae-89c06ed6d7a2">

### Additional context

Given the recommended version for Drupal 10 is Drush 12, it's probably worth adding in the template as well.

**Comment by gilzow** [comment]
Completed via #60
